### ISSUE TITLE
Support JDK > 8

### ISSUE THREAD

**Issue by msimmons** [msimmons/jvmcode#5]
Locations of jar files are changed to jmod files; src.zip in lib directory.  Detect versions of java > 8, allow user to say which jmods are excluded/included etc.

**Comment by msimmons** [comment]
Getting the following exception trying to deploy a verticle:

2019-10-28 16:20:19.135 [vert.x-eventloop-thread-0] ERROR net.contrapt.jvmcode.Application - Unhandled exception
java.lang.IllegalStateException: Current classloader must be URLClassLoader
	at io.vertx.core.impl.DeploymentManager.getClassLoader(DeploymentManager.java:401)
	at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:136)
	at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:677)
	at net.contrapt.jvmcode.RouterVerticle$startConsumers$7.handle(RouterVerticle.kt:146)
	at net.contrapt.jvmcode.RouterVerticle$startConsumers$7.handle(RouterVerticle.kt:20)
	at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:261)
	at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:239)
	at io.vertx.core.eventbus.impl.EventBusImpl$InboundDeliveryContext.next(EventBusImpl.java:565)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$5(EventBusImpl.java:524)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
